# Generated by Django 3.2.12 on 2024-06-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('SPORTS', 'SPORTS'), ('ATHLETICS', 'ATHLETICS')], default='Active', max_length=50)),
                ('no_of_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_of_admission', models.IntegerField()),
                ('admission_no', models.IntegerField()),
                ('uty_reg_no', models.CharField(max_length=50, unique=True)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('ALAPPUZHA', 'Alappuzha'), ('ERNAKULAM', 'Ernakulam'), ('IDUKKI', 'Idukki'), ('KANNUR', 'Kannur'), ('KASARAGOD', 'Kasaragod'), ('KOLLAM', 'Kollam'), ('KOTTAYAM', 'Kottayam'), ('KOZHIKODE', 'Kozhikode'), ('MALAPPURAM', 'Malappuram'), ('PALAKKAD', 'Palakkad'), ('PATHANAMTHITTA', 'Pathanamthitta'), ('THIRUVANANTHAPURAM', 'Thiruvananthapuram'), ('THRISSUR', 'Thrissur'), ('WAYANAD', 'Wayanad')], default='Active', max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.department')),
                ('programme_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Stud_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('uty_team_selection', models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.item')),
                ('stud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.student')),
            ],
        ),
    ]
