# Generated by Django 5.0.1 on 2024-06-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
