# Generated by Django 5.0.1 on 2024-06-08 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0002_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour_1', models.BooleanField(default=False)),
                ('hour_2', models.BooleanField(default=False)),
                ('hour_3', models.BooleanField(default=False)),
                ('hour_4', models.BooleanField(default=False)),
                ('hour_5', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.student')),
            ],
        ),
    ]
