# Generated by Django 5.0.1 on 2024-06-10 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0004_attendance_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(default=0, max_length=16, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 16 digits', regex='^\\d{16}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 15 digits', regex='^\\d{10,15}$')]),
        ),
    ]
