# Generated by Django 5.0.1 on 2024-06-10 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0005_student_aadhar_number_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 15 digits', regex='^\\d{10}$')]),
        ),
    ]
