# Generated by Django 5.0.1 on 2024-06-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0006_alter_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='team_pictures')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.item')),
            ],
        ),
    ]
