# Generated by Django 5.0.1 on 2024-06-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0007_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.item')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.student')),
            ],
            options={
                'unique_together': {('student', 'item')},
            },
        ),
    ]
