# Generated by Django 5.0.1 on 2024-06-14 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0008_studentteamassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_collected', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.item')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentTeamAssignment',
        ),
    ]
