# Generated by Django 5.0.1 on 2024-06-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0009_certificate_delete_studentteamassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.department'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='programme_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.programme'),
        ),
    ]
