# Generated by Django 5.0.1 on 2024-06-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0010_certificate_department_certificate_programme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='item_postion',
            field=models.CharField(choices=[('all_india_inter_university_1st', 'All India Inter University 1st'), ('all_india_inter_university_2nd', 'All India Inter University 2nd'), ('all_india_inter_university_3rd', 'All India Inter University 3rd'), ('all_india_inter_university_participation', 'All India Inter University participation'), ('south_zone_university_1st', 'South Zone University 1st'), ('south_zone_university_2nd', 'South Zone University 2nd'), ('south_zone_university_3rd', 'South Zone University 3rd'), ('south_zone_university_participation', 'South Zone University participation'), ('inter_collegiate_1st', 'Inter Collegiate 1st'), ('inter_collegiate_2nd', 'Inter Collegiate 2nd'), ('inter_collegiate_3rd', 'Inter Collegiate 3rd'), ('inter_collegiate_participation', 'Inter Collegiate participation')], default='Not Selected', max_length=40),
        ),
    ]
