# Generated by Django 5.0.1 on 2024-06-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0011_certificate_item_postion'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_item',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
