# Generated by Django 5.0.1 on 2024-06-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0012_stud_item_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
