# Generated by Django 5.0.1 on 2024-07-07 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0013_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(default=0, max_length=16, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 16 digits', regex='^\\d{12}$')]),
        ),
    ]
